# Base configs
baseurl: "https://akshanshnain.github.io/photography"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Akshansh Nain"
subtitle: "See the world through my eyes!"
author: "Akshansh Nain"
header:
 title: "Photography"
 subtitle: "Akshansh Nain"
footer:
 name: "Hey there, my name is Akshansh"
 bio: "I am a developer and a tech aficionado from India. Love making teeny tiny apps solving tiny problems in life and now learning photography."
web_design: "AJ"
social_urls:
  linkedin: "https://in.linkedin.com/in/akshansh-nain"
  github: "https://www.github.com/akshanshnain"

theme: jekyll-theme-modernist
