# Base configs
baseurl: "https://github.com/akshanshnain/akshanshnain.github.io.git"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Akshansh Nain"
subtitle: "See the world through my eyes!"
author: "Akshansh Nain"
header:
 title: "Photography"
 subtitle: "Akshansh Nain"
footer:
 name: "Hey there, my name is Ram"
 bio: "I am a developer and a tech aficionado from India. Love making teeny tiny apps solving tiny problems in life and now learning photography."
 github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork me on github</a> ;)"
web_design: "AJ"
social_urls:
  linkedin: "https://in.linkedin.com/in/akshansh-nain"
  github: "https://www.github.com/akshanshnain"
